name = "smiski-photos-worker"
main = "index.js"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

# Bind KV namespaces
kv_namespaces = [
  { binding = "IMAGE_LINKS", id = "6aa6f882d1364f40baa220d51664ea36" },
  { binding = "SECRETS", id = "69469b1204824e618c865e66be17e5c6" }
]

# Route configuration
routes = [
  { pattern = "*.smiski-travel.us/*", zone_id = "aefc459a2f48119ccd84f85f0173aee6" }
]

# Observability (logs)
[observability]
enabled = true
